name: Run Tests
on:
  push:
    branches: [ "main", "feature/280" ]
  pull_request:
    branches: [ "main" ]
env:
  HOST: localhost
  DATABASE: vetlog
  USER: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE $DATABASE;" -u$USER -p$PASSWORD
          echo "Creating user table"
          mysql -e "CREATE TABLE user(
            id bigint(20) NOT NULL AUTO_INCREMENT,
            account_non_expired bit(1) NOT NULL,
            account_non_locked bit(1) NOT NULL,
            credentials_non_expired bit(1) NOT NULL,
            date_created datetime NOT NULL,
            email varchar(255) DEFAULT NULL,
            enabled bit(1) NOT NULL,
            first_name varchar(255) DEFAULT NULL,
            last_name varchar(255) DEFAULT NULL,
            mobile varchar(255) DEFAULT NULL,
            password varchar(255) NOT NULL,
            role varchar(255) NOT NULL,
            username varchar(255) NOT NULL,
            PRIMARY KEY (id)
        );" -u$USER -p$PASSWORD -D$DATABASE
        echo "Creating users"
        mysql -e "INSERT INTO user VALUES(1, 0, 0, 0,'2024-04-21 20:08:51','contact@josdem.io', 1,'jose','morales',NULL,'password','USER','josdem');" -u$USER -p$PASSWORD -D$DATABASE
        mysql -e "INSERT INTO user VALUES(2, 0, 0, 0,'2024-04-21 20:08:52','contact@josdem.io', 1,'jose','morales',NULL,'password','USER','johndoe');" -u$USER -p$PASSWORD -D$DATABASE
        mysql -e "INSERT INTO user VALUES(3, 0, 0, 0,'2024-04-21 20:08:53','contact@josdem.io', 1,'jose','morales',NULL,'password','USER','NHUQfuLarRMDj');" -u$USER -p$PASSWORD -D$DATABASE
        mysql -e "INSERT INTO user VALUES(4, 0, 0, 0,'2024-04-21 20:08:54','contact@josdem.io', 1,'jose','morales',NULL,'password','USER','rJVyFMNsmXhPUvG');" -u$USER -p$PASSWORD -D$DATABASE
      - name: Build with Gradle
        run: ./gradlew test