name: Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  HOST: localhost
  DATABASE: vetlog
  USER: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Start MySQL
        run: |
            sudo /etc/init.d/mysql start
            mysql -uroot -e "CREATE DATABASE IF NOT EXISTS vetlog;"
            mysql -uroot -e "CREATE USER IF NOT EXISTS '${{ secrets.USERNAME }}'@'localhost' IDENTIFIED BY '${{ secrets.PASSWORD }}';"
            mysql -uroot -e "GRANT ALL PRIVILEGES ON vetlog.* TO '${{ secrets.USERNAME }}'@'localhost';"
            mysql -uroot -e "FLUSH PRIVILEGES;"
      - name: Set up MySQL
        run: ./gradlew -Dflyway.user=$USER -Dflyway.password=$PASSWORD -Dflyway.baselineOnMigrate=true flywayMigrate -i
      - name: Build with Gradle
        run: ./gradlew -Dflyway.user=$USER -Dflyway.password=$PASSWORD test jacocoTestReport sonar
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/
          retention-days: 30
      - name: SonarCloud Scan
        run: ./gradlew sonar \
          -Dsonar.projectKey=YOUR_PROJECT_KEY \
          -Dsonar.organization=YOUR_ORG \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      - name: Debug Secrets
        run: |
          echo "Database: vetlog"
          echo "User: ${{ secrets.USERNAME }}"
          echo "Password is set: $([ -n "${{ secrets.PASSWORD }}" ] && echo "Yes" || echo "No")"
          echo "Google Maps API Key is set: $([ -n "${{ secrets.GOOGLE_MAPS_API_KEY }}" ] && echo "Yes" || echo "No")"

